/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.powwow.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.powwow.model.PowwowMeetingOccurrence;
import com.liferay.powwow.model.PowwowMeetingOccurrenceModel;
import com.liferay.powwow.model.PowwowMeetingOccurrenceSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PowwowMeetingOccurrence service. Represents a row in the &quot;PowwowMeetingOccurrence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PowwowMeetingOccurrenceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PowwowMeetingOccurrenceImpl}.
 * </p>
 *
 * @author Shinn Lok
 * @see PowwowMeetingOccurrenceImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PowwowMeetingOccurrenceModelImpl
	extends BaseModelImpl<PowwowMeetingOccurrence>
	implements PowwowMeetingOccurrenceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a powwow meeting occurrence model instance should use the <code>PowwowMeetingOccurrence</code> interface instead.
	 */
	public static final String TABLE_NAME = "PowwowMeetingOccurrence";

	public static final Object[][] TABLE_COLUMNS = {
		{"occurrenceId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"calendarBookingId", Types.BIGINT}, {"powwowMeetingId", Types.BIGINT},
		{"zoomOriginalData", Types.VARCHAR},
		{"occurrenceStatus", Types.VARCHAR}, {"occurrenceApiId", Types.VARCHAR},
		{"startTime", Types.BIGINT}, {"endTime", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("occurrenceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("calendarBookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("powwowMeetingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("zoomOriginalData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occurrenceStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occurrenceApiId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("endTime", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PowwowMeetingOccurrence (occurrenceId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,calendarBookingId LONG,powwowMeetingId LONG,zoomOriginalData STRING null,occurrenceStatus VARCHAR(75) null,occurrenceApiId VARCHAR(75) null,startTime LONG,endTime LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table PowwowMeetingOccurrence";

	public static final String ORDER_BY_JPQL =
		" ORDER BY powwowMeetingOccurrence.startTime ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PowwowMeetingOccurrence.startTime ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.util.service.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.powwow.model.PowwowMeetingOccurrence"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.util.service.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.powwow.model.PowwowMeetingOccurrence"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.util.service.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.powwow.model.PowwowMeetingOccurrence"),
		true);

	public static final long ENDTIME_COLUMN_BITMASK = 1L;

	public static final long OCCURRENCESTATUS_COLUMN_BITMASK = 2L;

	public static final long POWWOWMEETINGID_COLUMN_BITMASK = 4L;

	public static final long STARTTIME_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PowwowMeetingOccurrence toModel(
		PowwowMeetingOccurrenceSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		PowwowMeetingOccurrence model = new PowwowMeetingOccurrenceImpl();

		model.setOccurrenceId(soapModel.getOccurrenceId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCalendarBookingId(soapModel.getCalendarBookingId());
		model.setPowwowMeetingId(soapModel.getPowwowMeetingId());
		model.setZoomOriginalData(soapModel.getZoomOriginalData());
		model.setOccurrenceStatus(soapModel.getOccurrenceStatus());
		model.setOccurrenceApiId(soapModel.getOccurrenceApiId());
		model.setStartTime(soapModel.getStartTime());
		model.setEndTime(soapModel.getEndTime());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PowwowMeetingOccurrence> toModels(
		PowwowMeetingOccurrenceSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<PowwowMeetingOccurrence> models =
			new ArrayList<PowwowMeetingOccurrence>(soapModels.length);

		for (PowwowMeetingOccurrenceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.util.service.ServiceProps.get(
			"lock.expiration.time.com.liferay.powwow.model.PowwowMeetingOccurrence"));

	public PowwowMeetingOccurrenceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _occurrenceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOccurrenceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _occurrenceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PowwowMeetingOccurrence.class;
	}

	@Override
	public String getModelClassName() {
		return PowwowMeetingOccurrence.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PowwowMeetingOccurrence, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PowwowMeetingOccurrence, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PowwowMeetingOccurrence, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PowwowMeetingOccurrence)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PowwowMeetingOccurrence, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PowwowMeetingOccurrence, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PowwowMeetingOccurrence)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PowwowMeetingOccurrence, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PowwowMeetingOccurrence, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PowwowMeetingOccurrence>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PowwowMeetingOccurrence.class.getClassLoader(),
			PowwowMeetingOccurrence.class, ModelWrapper.class);

		try {
			Constructor<PowwowMeetingOccurrence> constructor =
				(Constructor<PowwowMeetingOccurrence>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<PowwowMeetingOccurrence, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<PowwowMeetingOccurrence, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<PowwowMeetingOccurrence, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PowwowMeetingOccurrence, Object>>();
		Map<String, BiConsumer<PowwowMeetingOccurrence, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<PowwowMeetingOccurrence, ?>>();

		attributeGetterFunctions.put(
			"occurrenceId",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getOccurrenceId();
				}

			});
		attributeSetterBiConsumers.put(
			"occurrenceId",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object occurrenceId) {

					powwowMeetingOccurrence.setOccurrenceId((Long)occurrenceId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object companyId) {

					powwowMeetingOccurrence.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object userId) {

					powwowMeetingOccurrence.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object userName) {

					powwowMeetingOccurrence.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object createDate) {

					powwowMeetingOccurrence.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object modifiedDate) {

					powwowMeetingOccurrence.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"calendarBookingId",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getCalendarBookingId();
				}

			});
		attributeSetterBiConsumers.put(
			"calendarBookingId",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object calendarBookingId) {

					powwowMeetingOccurrence.setCalendarBookingId(
						(Long)calendarBookingId);
				}

			});
		attributeGetterFunctions.put(
			"powwowMeetingId",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getPowwowMeetingId();
				}

			});
		attributeSetterBiConsumers.put(
			"powwowMeetingId",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object powwowMeetingId) {

					powwowMeetingOccurrence.setPowwowMeetingId(
						(Long)powwowMeetingId);
				}

			});
		attributeGetterFunctions.put(
			"zoomOriginalData",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getZoomOriginalData();
				}

			});
		attributeSetterBiConsumers.put(
			"zoomOriginalData",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object zoomOriginalData) {

					powwowMeetingOccurrence.setZoomOriginalData(
						(String)zoomOriginalData);
				}

			});
		attributeGetterFunctions.put(
			"occurrenceStatus",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getOccurrenceStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"occurrenceStatus",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object occurrenceStatus) {

					powwowMeetingOccurrence.setOccurrenceStatus(
						(String)occurrenceStatus);
				}

			});
		attributeGetterFunctions.put(
			"occurrenceApiId",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getOccurrenceApiId();
				}

			});
		attributeSetterBiConsumers.put(
			"occurrenceApiId",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object occurrenceApiId) {

					powwowMeetingOccurrence.setOccurrenceApiId(
						(String)occurrenceApiId);
				}

			});
		attributeGetterFunctions.put(
			"startTime",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getStartTime();
				}

			});
		attributeSetterBiConsumers.put(
			"startTime",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object startTime) {

					powwowMeetingOccurrence.setStartTime((Long)startTime);
				}

			});
		attributeGetterFunctions.put(
			"endTime",
			new Function<PowwowMeetingOccurrence, Object>() {

				@Override
				public Object apply(
					PowwowMeetingOccurrence powwowMeetingOccurrence) {

					return powwowMeetingOccurrence.getEndTime();
				}

			});
		attributeSetterBiConsumers.put(
			"endTime",
			new BiConsumer<PowwowMeetingOccurrence, Object>() {

				@Override
				public void accept(
					PowwowMeetingOccurrence powwowMeetingOccurrence,
					Object endTime) {

					powwowMeetingOccurrence.setEndTime((Long)endTime);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getOccurrenceId() {
		return _occurrenceId;
	}

	@Override
	public void setOccurrenceId(long occurrenceId) {
		_occurrenceId = occurrenceId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCalendarBookingId() {
		return _calendarBookingId;
	}

	@Override
	public void setCalendarBookingId(long calendarBookingId) {
		_calendarBookingId = calendarBookingId;
	}

	@JSON
	@Override
	public long getPowwowMeetingId() {
		return _powwowMeetingId;
	}

	@Override
	public void setPowwowMeetingId(long powwowMeetingId) {
		_columnBitmask |= POWWOWMEETINGID_COLUMN_BITMASK;

		if (!_setOriginalPowwowMeetingId) {
			_setOriginalPowwowMeetingId = true;

			_originalPowwowMeetingId = _powwowMeetingId;
		}

		_powwowMeetingId = powwowMeetingId;
	}

	public long getOriginalPowwowMeetingId() {
		return _originalPowwowMeetingId;
	}

	@JSON
	@Override
	public String getZoomOriginalData() {
		if (_zoomOriginalData == null) {
			return "";
		}
		else {
			return _zoomOriginalData;
		}
	}

	@Override
	public void setZoomOriginalData(String zoomOriginalData) {
		_zoomOriginalData = zoomOriginalData;
	}

	@JSON
	@Override
	public String getOccurrenceStatus() {
		if (_occurrenceStatus == null) {
			return "";
		}
		else {
			return _occurrenceStatus;
		}
	}

	@Override
	public void setOccurrenceStatus(String occurrenceStatus) {
		_columnBitmask |= OCCURRENCESTATUS_COLUMN_BITMASK;

		if (_originalOccurrenceStatus == null) {
			_originalOccurrenceStatus = _occurrenceStatus;
		}

		_occurrenceStatus = occurrenceStatus;
	}

	public String getOriginalOccurrenceStatus() {
		return GetterUtil.getString(_originalOccurrenceStatus);
	}

	@JSON
	@Override
	public String getOccurrenceApiId() {
		if (_occurrenceApiId == null) {
			return "";
		}
		else {
			return _occurrenceApiId;
		}
	}

	@Override
	public void setOccurrenceApiId(String occurrenceApiId) {
		_occurrenceApiId = occurrenceApiId;
	}

	@JSON
	@Override
	public long getStartTime() {
		return _startTime;
	}

	@Override
	public void setStartTime(long startTime) {
		_columnBitmask = -1L;

		_startTime = startTime;
	}

	@JSON
	@Override
	public long getEndTime() {
		return _endTime;
	}

	@Override
	public void setEndTime(long endTime) {
		_columnBitmask |= ENDTIME_COLUMN_BITMASK;

		if (!_setOriginalEndTime) {
			_setOriginalEndTime = true;

			_originalEndTime = _endTime;
		}

		_endTime = endTime;
	}

	public long getOriginalEndTime() {
		return _originalEndTime;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PowwowMeetingOccurrence.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PowwowMeetingOccurrence toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PowwowMeetingOccurrence>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PowwowMeetingOccurrenceImpl powwowMeetingOccurrenceImpl =
			new PowwowMeetingOccurrenceImpl();

		powwowMeetingOccurrenceImpl.setOccurrenceId(getOccurrenceId());
		powwowMeetingOccurrenceImpl.setCompanyId(getCompanyId());
		powwowMeetingOccurrenceImpl.setUserId(getUserId());
		powwowMeetingOccurrenceImpl.setUserName(getUserName());
		powwowMeetingOccurrenceImpl.setCreateDate(getCreateDate());
		powwowMeetingOccurrenceImpl.setModifiedDate(getModifiedDate());
		powwowMeetingOccurrenceImpl.setCalendarBookingId(
			getCalendarBookingId());
		powwowMeetingOccurrenceImpl.setPowwowMeetingId(getPowwowMeetingId());
		powwowMeetingOccurrenceImpl.setZoomOriginalData(getZoomOriginalData());
		powwowMeetingOccurrenceImpl.setOccurrenceStatus(getOccurrenceStatus());
		powwowMeetingOccurrenceImpl.setOccurrenceApiId(getOccurrenceApiId());
		powwowMeetingOccurrenceImpl.setStartTime(getStartTime());
		powwowMeetingOccurrenceImpl.setEndTime(getEndTime());

		powwowMeetingOccurrenceImpl.resetOriginalValues();

		return powwowMeetingOccurrenceImpl;
	}

	@Override
	public int compareTo(PowwowMeetingOccurrence powwowMeetingOccurrence) {
		int value = 0;

		if (getStartTime() < powwowMeetingOccurrence.getStartTime()) {
			value = -1;
		}
		else if (getStartTime() > powwowMeetingOccurrence.getStartTime()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PowwowMeetingOccurrence)) {
			return false;
		}

		PowwowMeetingOccurrence powwowMeetingOccurrence =
			(PowwowMeetingOccurrence)obj;

		long primaryKey = powwowMeetingOccurrence.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PowwowMeetingOccurrenceModelImpl powwowMeetingOccurrenceModelImpl =
			this;

		powwowMeetingOccurrenceModelImpl._setModifiedDate = false;

		powwowMeetingOccurrenceModelImpl._originalPowwowMeetingId =
			powwowMeetingOccurrenceModelImpl._powwowMeetingId;

		powwowMeetingOccurrenceModelImpl._setOriginalPowwowMeetingId = false;

		powwowMeetingOccurrenceModelImpl._originalOccurrenceStatus =
			powwowMeetingOccurrenceModelImpl._occurrenceStatus;

		powwowMeetingOccurrenceModelImpl._originalEndTime =
			powwowMeetingOccurrenceModelImpl._endTime;

		powwowMeetingOccurrenceModelImpl._setOriginalEndTime = false;

		powwowMeetingOccurrenceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PowwowMeetingOccurrence> toCacheModel() {
		PowwowMeetingOccurrenceCacheModel powwowMeetingOccurrenceCacheModel =
			new PowwowMeetingOccurrenceCacheModel();

		powwowMeetingOccurrenceCacheModel.occurrenceId = getOccurrenceId();

		powwowMeetingOccurrenceCacheModel.companyId = getCompanyId();

		powwowMeetingOccurrenceCacheModel.userId = getUserId();

		powwowMeetingOccurrenceCacheModel.userName = getUserName();

		String userName = powwowMeetingOccurrenceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			powwowMeetingOccurrenceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			powwowMeetingOccurrenceCacheModel.createDate = createDate.getTime();
		}
		else {
			powwowMeetingOccurrenceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			powwowMeetingOccurrenceCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			powwowMeetingOccurrenceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		powwowMeetingOccurrenceCacheModel.calendarBookingId =
			getCalendarBookingId();

		powwowMeetingOccurrenceCacheModel.powwowMeetingId =
			getPowwowMeetingId();

		powwowMeetingOccurrenceCacheModel.zoomOriginalData =
			getZoomOriginalData();

		String zoomOriginalData =
			powwowMeetingOccurrenceCacheModel.zoomOriginalData;

		if ((zoomOriginalData != null) && (zoomOriginalData.length() == 0)) {
			powwowMeetingOccurrenceCacheModel.zoomOriginalData = null;
		}

		powwowMeetingOccurrenceCacheModel.occurrenceStatus =
			getOccurrenceStatus();

		String occurrenceStatus =
			powwowMeetingOccurrenceCacheModel.occurrenceStatus;

		if ((occurrenceStatus != null) && (occurrenceStatus.length() == 0)) {
			powwowMeetingOccurrenceCacheModel.occurrenceStatus = null;
		}

		powwowMeetingOccurrenceCacheModel.occurrenceApiId =
			getOccurrenceApiId();

		String occurrenceApiId =
			powwowMeetingOccurrenceCacheModel.occurrenceApiId;

		if ((occurrenceApiId != null) && (occurrenceApiId.length() == 0)) {
			powwowMeetingOccurrenceCacheModel.occurrenceApiId = null;
		}

		powwowMeetingOccurrenceCacheModel.startTime = getStartTime();

		powwowMeetingOccurrenceCacheModel.endTime = getEndTime();

		return powwowMeetingOccurrenceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PowwowMeetingOccurrence, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PowwowMeetingOccurrence, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PowwowMeetingOccurrence, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((PowwowMeetingOccurrence)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PowwowMeetingOccurrence, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PowwowMeetingOccurrence, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PowwowMeetingOccurrence, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((PowwowMeetingOccurrence)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, PowwowMeetingOccurrence>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _occurrenceId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _calendarBookingId;
	private long _powwowMeetingId;
	private long _originalPowwowMeetingId;
	private boolean _setOriginalPowwowMeetingId;
	private String _zoomOriginalData;
	private String _occurrenceStatus;
	private String _originalOccurrenceStatus;
	private String _occurrenceApiId;
	private long _startTime;
	private long _endTime;
	private long _originalEndTime;
	private boolean _setOriginalEndTime;
	private long _columnBitmask;
	private PowwowMeetingOccurrence _escapedModel;

}