include-and-override=portlet-ext.properties

#
# Set the interval to check for Powwow meetings have end time passed. The
# value is set in one minute increments.
#
powwow.endtime.synchronization.interval=60

#
# Configure invitiation email notification settings.
#
powwow.invitation.email.body=com/liferay/powwow/dependencies/meeting_scheduled_notification_body.tmpl
powwow.invitation.email.subject=com/liferay/powwow/dependencies/meeting_scheduled_notification_subject.tmpl

#
# Enter the group name, friendly URL, and privacy of a page that will be used to
# create Powwow meeting invitations. If none is specified, the first public
# layout from the Guest group will be used.
#
powwow.invitation.group.name=
powwow.invitation.layout.friendly.url=
powwow.invitation.layout.private=

#
# Set the interval to auto update occurrence status to completed. The value is
# set in one hour increments.
#
powwow.meeting.occurrence.synchronization.interval=4

#
# Set the number of retries to perform an API call in case it fails.
#
powwow.provider.api.retry.attempts=3

#
# Set the interval to retry an API call in milliseconds.
#
powwow.provider.api.retry.interval=30000

#
# Set time to live for API token in second.
#
powwow.provider.api.token.time.to.live=90

#
# Set the interval to check for Powwow server updates. The value is set in one
# minute increments.
#
powwow.synchronization.interval=5

resource.actions.configs=resource-actions/default.xml

zoom.api.callback.login=
zoom.api.callback.password=