portlet.add.default.resource.check.whitelist=1_WAR_powwowportlet

value.object.listener.com.liferay.powwow.model.PowwowMeetingOccurrenceModelListener=com.liferay.powwow.model.PowwowMeetingOccurrenceModelListener