/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.powwow.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PowwowMeetingOccurrence service. Represents a row in the &quot;PowwowMeetingOccurrence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.powwow.model.impl.PowwowMeetingOccurrenceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.powwow.model.impl.PowwowMeetingOccurrenceImpl</code>.
 * </p>
 *
 * @author Shinn Lok
 * @see PowwowMeetingOccurrence
 * @generated
 */
@ProviderType
public interface PowwowMeetingOccurrenceModel
	extends AuditedModel, BaseModel<PowwowMeetingOccurrence>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a powwow meeting occurrence model instance should use the {@link PowwowMeetingOccurrence} interface instead.
	 */

	/**
	 * Returns the primary key of this powwow meeting occurrence.
	 *
	 * @return the primary key of this powwow meeting occurrence
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this powwow meeting occurrence.
	 *
	 * @param primaryKey the primary key of this powwow meeting occurrence
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the occurrence ID of this powwow meeting occurrence.
	 *
	 * @return the occurrence ID of this powwow meeting occurrence
	 */
	public long getOccurrenceId();

	/**
	 * Sets the occurrence ID of this powwow meeting occurrence.
	 *
	 * @param occurrenceId the occurrence ID of this powwow meeting occurrence
	 */
	public void setOccurrenceId(long occurrenceId);

	/**
	 * Returns the company ID of this powwow meeting occurrence.
	 *
	 * @return the company ID of this powwow meeting occurrence
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this powwow meeting occurrence.
	 *
	 * @param companyId the company ID of this powwow meeting occurrence
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this powwow meeting occurrence.
	 *
	 * @return the user ID of this powwow meeting occurrence
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this powwow meeting occurrence.
	 *
	 * @param userId the user ID of this powwow meeting occurrence
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this powwow meeting occurrence.
	 *
	 * @return the user uuid of this powwow meeting occurrence
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this powwow meeting occurrence.
	 *
	 * @param userUuid the user uuid of this powwow meeting occurrence
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this powwow meeting occurrence.
	 *
	 * @return the user name of this powwow meeting occurrence
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this powwow meeting occurrence.
	 *
	 * @param userName the user name of this powwow meeting occurrence
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this powwow meeting occurrence.
	 *
	 * @return the create date of this powwow meeting occurrence
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this powwow meeting occurrence.
	 *
	 * @param createDate the create date of this powwow meeting occurrence
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this powwow meeting occurrence.
	 *
	 * @return the modified date of this powwow meeting occurrence
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this powwow meeting occurrence.
	 *
	 * @param modifiedDate the modified date of this powwow meeting occurrence
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the calendar booking ID of this powwow meeting occurrence.
	 *
	 * @return the calendar booking ID of this powwow meeting occurrence
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this powwow meeting occurrence.
	 *
	 * @param calendarBookingId the calendar booking ID of this powwow meeting occurrence
	 */
	public void setCalendarBookingId(long calendarBookingId);

	/**
	 * Returns the powwow meeting ID of this powwow meeting occurrence.
	 *
	 * @return the powwow meeting ID of this powwow meeting occurrence
	 */
	public long getPowwowMeetingId();

	/**
	 * Sets the powwow meeting ID of this powwow meeting occurrence.
	 *
	 * @param powwowMeetingId the powwow meeting ID of this powwow meeting occurrence
	 */
	public void setPowwowMeetingId(long powwowMeetingId);

	/**
	 * Returns the zoom original data of this powwow meeting occurrence.
	 *
	 * @return the zoom original data of this powwow meeting occurrence
	 */
	@AutoEscape
	public String getZoomOriginalData();

	/**
	 * Sets the zoom original data of this powwow meeting occurrence.
	 *
	 * @param zoomOriginalData the zoom original data of this powwow meeting occurrence
	 */
	public void setZoomOriginalData(String zoomOriginalData);

	/**
	 * Returns the occurrence status of this powwow meeting occurrence.
	 *
	 * @return the occurrence status of this powwow meeting occurrence
	 */
	@AutoEscape
	public String getOccurrenceStatus();

	/**
	 * Sets the occurrence status of this powwow meeting occurrence.
	 *
	 * @param occurrenceStatus the occurrence status of this powwow meeting occurrence
	 */
	public void setOccurrenceStatus(String occurrenceStatus);

	/**
	 * Returns the occurrence api ID of this powwow meeting occurrence.
	 *
	 * @return the occurrence api ID of this powwow meeting occurrence
	 */
	@AutoEscape
	public String getOccurrenceApiId();

	/**
	 * Sets the occurrence api ID of this powwow meeting occurrence.
	 *
	 * @param occurrenceApiId the occurrence api ID of this powwow meeting occurrence
	 */
	public void setOccurrenceApiId(String occurrenceApiId);

	/**
	 * Returns the start time of this powwow meeting occurrence.
	 *
	 * @return the start time of this powwow meeting occurrence
	 */
	public long getStartTime();

	/**
	 * Sets the start time of this powwow meeting occurrence.
	 *
	 * @param startTime the start time of this powwow meeting occurrence
	 */
	public void setStartTime(long startTime);

	/**
	 * Returns the end time of this powwow meeting occurrence.
	 *
	 * @return the end time of this powwow meeting occurrence
	 */
	public long getEndTime();

	/**
	 * Sets the end time of this powwow meeting occurrence.
	 *
	 * @param endTime the end time of this powwow meeting occurrence
	 */
	public void setEndTime(long endTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PowwowMeetingOccurrence powwowMeetingOccurrence);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PowwowMeetingOccurrence> toCacheModel();

	@Override
	public PowwowMeetingOccurrence toEscapedModel();

	@Override
	public PowwowMeetingOccurrence toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}